import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/providers/AuthProvider';
import { ToastContainer, Slide } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { QueryProvider } from '@/context/providers/QueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistSans.variable} antialiased`}>
        <QueryProvider>
          <AuthProvider>
            {children}
            <ToastContainer
              className="custom-toast"
              position="top-right"
              autoClose={1000}
              hideProgressBar={true}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              theme="light"
              transition={Slide}
            />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
